# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    # Installing SlimerJS
    - name: SlimerJS
      run: |
        wget https://ftp.mozilla.org/pub/firefox/releases/58.0/linux-x86_64/en-US/firefox-58.0.tar.bz2
        mkdir ~/slimerfox
        tar -C ~/slimerfox -xvjf firefox-58.0.tar.bz2
        rm firefox-58.0.tar.bz2
    # Installing xvfb
    - name: Installing xvfb
      run: |
        sudo apt-get install xvfb
    # Installing npm packages
    - name: Installing npm packages
      run: |
        npm install
    # Update the test environment, remove old files, and build again.
    - name: Build
      run: |
        cp lib/ccNetViz.js ci_test/lib/ccNetViz.js
        rm lib/ccNetViz.js
        rm lib/ccNetViz.js.map
        npm run build
    # Build informations
    - name: Build informations
      run: |
        node -v
        npm -v
    # Running tests
    - name: Test
      run: |
        export SLIMERJSLAUNCHER=~/slimerfox/firefox/firefox
        npm run test images=$(ls ci_test/scenarios -p | grep -v / | tr '\n' ',') animations=$(ls ci_test/animation_scenarios -p | grep -v / | tr '\n' ',')
    # Set this step as comment line for debug mode.
    - name: Removing temporary files
      run: |
        rm -rf ci_test/animation_frames
        rm -rf ci_test/frames
        rm ci_test/slimer/temp/animations.js
        rm ci_test/slimer/temp/images.js
        touch ci_test/slimer/temp/animations.js
        touch ci_test/slimer/temp/images.js
    - name: Output variables
      id: vars
      run: |
        echo ::set-output name=pr_date::"$(date +%d-%m-%Y)"
    - name: Update ccNetViz.js
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Updating ccNetViz.js
        title: Update ccNetViz.js
        labels: automated pr
        body: This PR auto-generated on ${{ steps.vars.outputs.pr_date }}
        branch: test
